# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestGitApi' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestGitApi
pod 'Alamofire'
pod 'SwiftyJSON'

  target 'TestGitApiTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
